# Chapter 10 LU Factorization

In [1]:
import numpy as np

In [2]:
def LU_decomposition(a):
    a = a.copy()
    m, n = a.shape
    for k in range(n-1):
        for i in range(k + 1, n):
            factor = a[i, k] / a[k, k]
            a[i, k+1:] -= factor * a[k, k+1:]
            a[i, k] = factor
    return a

In [3]:
def LU_solve(a, b):
    b = b.copy()
    m, n = a.shape
    for k in range(n):
        b[k] -= np.dot(a[k,:k], b[:k])
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - np.dot(a[k,k+1:], b[k+1:]))/a[k,k]
    return b

In [4]:
a = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])
ad = LU_decomposition(a)

b = np.array([7.85, -19.3, 71.4])
x = LU_solve(ad, b)
print(x)

[ 3.  -2.5  7. ]


In [5]:
U = np.triu(ad)
L = np.tril(ad) - np.diag(np.diag(ad)) + np.eye(ad.shape[0])
print(a == np.dot(L, U))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Cholesky Factorization

In [6]:
def cholesky(a):
    """ matrix a must be symmetric positive-definite """
    n = a.shape[0]
    u = np.zeros((n,n))
    for i in range(n):
        temp = a[i,i] - np.dot(u[:i,i], u[:i,i])
        if temp <= 0:
            print('error : ~~')
        u[i,i] = np.sqrt(temp)
        for j in range(i+1, n):
            u[i,j] = (a[i,j] - np.dot(u[:i,i], u[:i,j])) / u[i,i]
    return u

In [7]:
a = np.array([[16, 15, 55],[15, 55, 225], [55, 225, 1000]])
# check eigenvalues, for positive-definite matrix, all eigenvalues are positive
print(np.linalg.eigvals(a)) 
u = cholesky(a)
np.round(a - np.dot(u.T, u),10)

[1053.96173576   13.54448382    3.49378041]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Chapter 11 Matrix Inverse and Condition

### Inverse mastrix by LU-Factorization 

In [8]:
def inverse_by_LU(a):
    a = a.copy()
    n =a.shape[0]
    a = LU_decomposition(a)
    e = np.eye(n)
    b = np.zeros((n,n))
    for i in range(n):
        b[:,i] = LU_solve(a, e[i])
    return b

In [9]:
a = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])
b = inverse_by_LU(a)
np.round(np.dot(a, b), 8)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [10]:
# numpy array, norm
x = np.array([1, 2, 3])
print(x.sum())    
print((x**2).sum())
print(np.sqrt((x**2).sum()))
print(np.linalg.norm(x))

6
14
3.7416573867739413
3.7416573867739413


In [8]:
# example 11.3, Hilbert matrix
def hilbert(n):
    A = np.zeros((n,n))    
    for i in range(n):
        for j in range(n):
            A[i,j] = 1/(i+j+1)
    return A

In [12]:
for n in range(2, 21, 2):
    A = hilbert(n)
    cond = np.linalg.cond(A)
    B = np.linalg.inv(A)
    x = np.abs((B.dot(A))).sum()
    print("{0:5d} {1:15.3f} {2:15.4e}".format(n, x, cond))

    2           2.000      1.9281e+01
    4           4.000      1.5514e+04
    6           6.000      1.4951e+07
    8           8.000      1.5258e+10
   10          10.007      1.6025e+13
   12          51.972      1.6212e+16
   14        1992.441      2.5515e+17
   16       23500.047      4.8875e+17
   18       58955.608      1.3500e+18
   20      561252.143      2.1065e+18


## Python Function

**scipy.linalg**

Basics

> inv(a[, overwrite_a, check_finite])	Compute the inverse of a matrix.

> solve(a, b[, sym_pos, lower, overwrite_a, ...])	Solves the linear equation set a * x = b for the unknown x for square a matrix.

> det(a[, overwrite_a, check_finite])	Compute the determinant of a matrix

> norm(a[, ord, axis, keepdims])	Matrix or vector norm.

> tril(m[, k])	Make a copy of a matrix with elements above the k-th diagonal zeroed.

> triu(m[, k])	Make a copy of a matrix with elements below the k-th diagonal zeroed.

Decompositions

> lu(a[, permute_l, overwrite_a, check_finite])	Compute pivoted LU decomposition of a matrix.

> svd(a[, full_matrices, compute_uv, ...])	Singular Value Decomposition.

> cholesky(a[, lower, overwrite_a, check_finite])	Compute the Cholesky decomposition of a matrix.

> qr(a[, overwrite_a, lwork, mode, pivoting, ...])	Compute QR decomposition of a matrix.

> hessenberg(a[, calc_q, overwrite_a, ...])	Compute Hessenberg form of a matrix.
